# .github/labeler.yml

# Label for documentation changes
documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**'
      - 'img'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      

# Label for Docker changes
docker:
  - changed-files:
    - any-glob-to-any-file:
      - '*docker*'
      - 'Docker*'
      - 'docker-compose.yaml'
      - 'Dockerfile'

# Label for release-related changes
release:
  - changed-files:
    - any-glob-to-any-file:
      - 'scraibe_webui/**'
      - 'pyproject.toml'
      - 'LICENCE'

tests:
  - changed-files:
    - any-glob-to-any-file:
      - 'tests/**'
      
workflows:
  - changed-files:
      - any-glob-to-any-file:
        - '.github/workflows/*'
        - '.github/*'

github: 
  - changed-files:
      - any-glob-to-any-file:
        - '.gitignore'
        - '.github/ISSUE_TEMPLATE/*'

dependencies: 
  - changed-files:
      - any-glob-to-any-file:
        - 'requirements.txt'
        - 'pyproject.toml'

feature:
 - head-branch: ['^feature', 'feature']

patch:
  - head-branch: ['^patch', 'patch', '^bug', 'bug']

ignore-pr-title-for-release: 
  - head-branch: ['develop']
  - base-branch: ['main']