services:
    scraibe:
      # you can set a UID/GID in an .env file
      user: "${UID}:${GID}"
      entrypoint: ./run_docker.sh
      build: .
      environment: 
        - AUTOT_CACHE=/data/models/
      container_name: scraibe_large
      ports:
        - '80:7860'
      volumes: 
        - type: bind
          source: data/
          target: /data/
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
