services:
    scraibe:
      # you can set a UID/GID in an .env file
      # user: "${UID}:${GID}"
      build: .
      container_name: scraibe_large
      ports:
        - '7860:7860'
      volumes: 
        - ./data:/data 
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
